#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
using namespace std;


bool isSorted(int checkingArray[], int size)
{
	bool isSortedArray = true;
	for (int i = 1; i < size; i++)
	{
		if (checkingArray[i - 1] > checkingArray[i])
		{
			isSortedArray = false;
			break;
		}
	}
	return isSortedArray;
}

void autoGeneratedCheck()
{
	srand(0);

	const int debugNumber = 10;
	const int maxRandomArrayElement = 25;
	const int maxArraySize = 20;

	for (int i = 0; i < debugNumber; i++)
	{
		const int arraySize = rand() % maxArraySize;
		int *checkingArray = new int[arraySize];

		for (int j = 0; j < arraySize; j++)
		{
			checkingArray[j] = rand() % maxRandomArrayElement;
		}

		bubbleSort(checkingArray, arraySize);

		if (!isSorted(checkingArray, arraySize))
		{
			printArray("Wrong test sort: ", checkingArray, 0, arraySize - 1);
			delete[] checkingArray;
			exit(1);
		}

		delete[] checkingArray;
	}
}

void checkFromFile()
{
	vector<string> data;
	readFile("checkData.txt", data);

	vector<string> results;
	readFile("resultData.txt", results);

	auto i_data = data.begin();
	auto i_results = results.begin();
	while (i_data != data.end() && i_results != results.end())
	{

		if (0)
		{
			cout << "Mistakes";
			exit(1);
		}
		++i_data;
		++i_results;
	}
}