#include "pch.h"
#include <iostream>
#include <string>
#include <sstream>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
#include "AVLTree.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> data;
	readFile("checkData.txt", data);

	vector<string> results;
	readFile("resultData.txt", results);

	auto iData = data.begin();
	auto iResults = results.begin();
	while (iData != data.end() && iResults != results.end())
	{
		AVLTree tree;

		vector<string> data;
		readFileByLines(*iData, data);

		for (const auto &i : data)
		{
			stringstream str;
			str << i;

			string data;
			str >> data;

			string key;
			str >> key;

			tree.add(data, key);
		}

		tree.printAll("checkFile.txt");

		vector<string> answer;
		readFileByLines("checkFile.txt", answer);
		
		vector<string> result;
		readFileByLines(*iResults, result);

		if (answer != result)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}