#include "pch.h"
#include "mainFunctions.h"
#include <iostream>

const int debugNumber = 10;

void autoGeneratedCheck()
{
	srand(0);

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	FILE *inputDataFile = fopen("data.txt", "r");
	if (!inputDataFile)
	{
		printf("File not fount");
		exit(1);
	}

	char *data[100] = {};
	int linesRead = 0;

	while (!feof(inputDataFile))
	{
		char *buffer = new char[100];
		const int readBytes = fscanf(inputDataFile, "%[^\n]", buffer);
		if (readBytes < 0)
		{
			break;
		}
		data[linesRead++] = buffer;
	}

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		
	}

	
	fclose(inputDataFile);
}