#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
#include "DoubleLinkedList.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<vector<int> > data;
	readCheckingFile("checkData.txt", data);

	vector<string> results;
	readFile("resultData.txt", results);

	auto i_data = data.begin();
	auto i_results = results.begin();
	while (i_data != data.end() && i_results != results.end())
	{
		DoubleLinkedList checkingList;
		for (auto const &i : *i_data)
		{
			checkingList.push_back(i);
		}

		if ((((*i_results) == "1") ? true : false) != checkingList.isSymmetric())
		{
			checkingList.deleteAllList();
			cout << "Mistakes";
			exit(1);
		}
		++i_data;
		++i_results;
		checkingList.deleteAllList();
	}
}