#include "pch.h"
#include <iostream>
#include "main.h"
#include "algorithms.h"
#include "readFile.h"


void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 100;
	const int maxRandomNumber = 32;

	for (int i = 0; i < debugNumber; i++)
	{
		int number1 = rand() % maxRandomNumber - rand() % maxRandomNumber;
		int number2 = rand() % maxRandomNumber - rand() % maxRandomNumber;

		int *bitNumber1 = nullptr;
		int *bitNumber2 = nullptr;

		decToTwosComplement(number1, &bitNumber1);
		decToTwosComplement(number2, &bitNumber2);

		int *addResult = nullptr;
		addBitNumbers(bitNumber1, bitNumber2, &addResult);

		const int bitSum = twosComplementToDec(addResult);
		const int numberSum = number1 + number2;

		if (bitSum != numberSum)
		{
			printf("Где-то ошибки");
			delete[] bitNumber1;
			delete[] bitNumber2;
			delete[] addResult;
			exit(1);
		}

		delete[] bitNumber1;
		delete[] bitNumber2;
		delete[] addResult;
	}
}

void checkFromFile()
{
	char *data[100] = {};
	const int linesRead = readFile("checkData.txt", data);

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		if (0)
		{
			exit(1);
		}
	}
}