#include "pch.h"
#include <iostream>
#include "mainFunctions.h"
#include "algorithms.h"

const int debugNumber = 10;
const int maxNumber = 100;

void autoGeneratedCheck()
{
	srand(0);

	
	for (int i = 0; i < debugNumber; i++)
	{

		const int firstNumber = rand() % maxNumber;
		const int secondNumber = rand() % maxNumber;

		//размер 1-го числа
		int number = firstNumber;
		int counter = 0;
		while (number > 0)
		{
			number /= 2;
			counter++;
		}
		int *firstNumberBitArray = new int[counter] {};
		const int firstArraySize = counter;

		//размер 2-го числа
		number = secondNumber;
		counter = 0;
		while (number > 0)
		{
			number /= 2;
			counter++;
		}
		int *secondNumberBitArray = new int[counter] {};
		const int secondArraySize = counter;

		//записываем числа в битах
		printBitView(firstNumberBitArray, firstArraySize, firstNumber);
		printBitView(secondNumberBitArray, secondArraySize, secondNumber);


		int maxNumber = 0;
		if (firstArraySize != secondArraySize)
		{
			if (firstArraySize > secondArraySize)
			{
				maxNumber = 1;
			}
			else
			{
				maxNumber = 2;
			}
		}
		else
		{
			maxNumber = compareBitView(firstNumberBitArray, secondNumberBitArray, firstArraySize);
		}

		bool checkResult = (firstNumber == secondNumber && maxNumber == 0) || (firstNumber > secondNumber && maxNumber == 1) || (firstNumber < secondNumber && maxNumber == 2);
		if (!checkResult)
		{
			printf("Mistakes\n");
			delete[] firstNumberBitArray;
			delete[] secondNumberBitArray;
			exit(1);
		}


		delete[] firstNumberBitArray;
		delete[] secondNumberBitArray;
	}

}

void checkFromFile()
{
	FILE *inputDataFile = fopen("data.txt", "r");
	if (!inputDataFile)
	{
		printf("File not fount");
		exit(1);
	}

	char *data[100] = {};
	int linesRead = 0;

	while (!feof(inputDataFile))
	{
		char *buffer = new char[100];
		const int readBytes = fscanf(inputDataFile, "%[^\n]", buffer);
		if (readBytes < 0)
		{
			break;
		}
		data[linesRead++] = buffer;
	}

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		
	}

	
	fclose(inputDataFile);
}