#include "pch.h"
#include <iostream>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"


void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	char *data[100] = {};
	const int linesRead = readFile("checkData.txt", data);

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		if (0)
		{
			exit(1);
		}
	}
}