#include "pch.h"
#include <iostream>
#include <string>
#include <sstream>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
#include "ExpressionTree.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> data;
	readFile("checkData.txt", data);

	vector<string> results;
	readFile("resultData.txt", results);

	auto iData = data.begin();
	auto iResults = results.begin();
	while (iData != data.end() && iResults != results.end())
	{
		ExpressionTree tree;

		tree.readExpressionTree(*iData);

		int result = 0;
		stringstream str;
		str << *iResults;
		str >> result;

		if (tree.countExpression() != result)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}