#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
#include "HashTable.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> checkData;
	readFileByLines("checkData.txt", checkData);

	vector<string> checkResults;
	readFileByLines("resultData.txt", checkResults);

	auto iData = checkData.begin();
	auto iResults = checkResults.begin();
	while (iData != checkData.end() && iResults != checkResults.end())
	{
		HashTable table;

		vector<string> data;
		readFile(*iData, data);

		for (const auto &i : data)
		{
			table.add(i);
		}
		table.printAllData("checkFile.txt");


		vector<string> answer;
		readFileByLines("checkFile.txt", answer);
		
		vector<string> result;
		readFileByLines(*iResults, result);

		if (answer != result)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}