#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> checkData;
	readFile("checkData.txt", checkData);

	vector<string> checkResults;
	readFile("resultData.txt", checkResults);

	auto iData = checkData.begin();
	auto iResults = checkResults.begin();
	while (iData != checkData.end() && iResults != checkResults.end())
	{
		vector<string> data;
		readFileByLines(*iData, data);

		string dataString = data[0];
		data.erase(data.begin());

		vector<string> result;
		readFileByLines(*iResults, result);

		findFirstEntranceInFile(data, dataString, "checkFile.txt");

		vector<string> answer;
		readFileByLines("checkFile.txt", answer);
		
		if (answer != result)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}