#include "pch.h"
#include <iostream>
#include "mainFunctions.h"
#include "algorithms.h"
#include "readFile.h"



void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	char *data[100] = {};
	const int linesRead = readFile("checkData.txt", data);

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		char *buffer = data[linesCounter];
		int *enteredArray = nullptr;
		int arraySize = 0;

		processInputString(buffer, &enteredArray, &arraySize);

		quickSort(enteredArray, 0, arraySize - 1);

		if (!isSorted(enteredArray, arraySize))
		{
			printf("Где-то ошибки");
			delete[] enteredArray;
			exit(1);
		}

		delete[] enteredArray;
	}
}