#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> checkData;
	readFile("checkData.txt", checkData);

	vector<string> resultData;
	readFile("resultData.txt", resultData);

	auto iData = checkData.begin();
	auto iResults = resultData.begin();
	while (iData != checkData.end() && iResults != resultData.end())
	{
		BinarySearchTree tree;

		vector<string> data;
		readFile(*iData, data);

		for (const auto &i : data)
		{
			stringstream str;
			str << i;

			int number = 0;
			str >> number;

			tree.add(number);
		}

		ofstream outputFile("checkFile.txt", ios::trunc);
		outputFile.close();

		tree.printAll(true, nullptr, "checkFile.txt");

		vector<string> answerCheck;
		readFileByLines("checkFile.txt", answerCheck);

		vector<string> resultCheck;
		readFileByLines(*iResults, resultCheck);

		if (answerCheck != resultCheck)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}