#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include <sstream>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	List list;
	vector<string> data;
	readFile("checkData.txt", data);

	auto iData = data.begin();
	while (iData != data.end())
	{
		stringstream str;

		string name;
		str << *iData;
		++iData;
		str >> name;
		str.clear();

		string phoneNumber;
		str << *iData;
		++iData;
		str >> phoneNumber;
		str.clear();

		list.pushBack(name, phoneNumber);

		list.mergeSort();
		bool isRightSortedByNames = list.isSorted();
		list.mergeSort(false);
		bool isRightSortedByNumbers = list.isSorted(false);

		if (!(isRightSortedByNames && isRightSortedByNumbers))
		{
			cout << "Mistakes";
			exit(1);
		}
	}
}