#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
#include "SinglyConnectedList.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void addNumberFromStringToList(string &str, SinglyConnectedList &list)
{
	int number = 0;
	bool isRead = false;
	for (auto const i : str)
	{
		if (isspace(i))
		{
			if (isRead)
			{
				list.push_back(number);
			}
			number = 0;
			isRead = false;
		}

		if (isdigit(i))
		{
			isRead = true;
			number = number * 10 + i - '0';
		}
	}
}

void checkFromFile()
{
	vector<string> data;
	readFile("checkData.txt", data);

	vector<string> results;
	readFile("resultData.txt", results);

	auto iData = data.begin();
	auto iResults = results.begin();
	while (iData != data.end() && iResults != results.end())
	{
		SinglyConnectedList checkingList;
		SinglyConnectedList resultList;
		
		addNumberFromStringToList(*iData, checkingList);
		addNumberFromStringToList(*iResults, resultList);

		checkingList.reverse();

		if (!(checkingList == resultList))
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}