#pragma once
#include "SinglyConnectedList.h"
#include <iostream>
#include <string>

void checkFromFile();

void autoGeneratedCheck();

void addNumberFromStringToList(std::string &str, SinglyConnectedList &list);
