#include "pch.h"
#include <iostream>
#include <string>
#include <vector>
#include "algorithms.h"
#include "readFile.h"
#include "check.h"
using namespace std;

void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	vector<string> checkData;
	readFile("checkData.txt", checkData);

	vector<string> resultData;
	readFile("resultData.txt", resultData);

	auto iData = checkData.begin();
	auto iResults = resultData.begin();
	while (iData != checkData.end() && iResults != resultData.end())
	{
		Graph map;
		readGraphFromFile(*iData, map);
		auto dyingTree = makeDyingTree(map, 0);
		printAllEdges(*dyingTree, "checkFile.txt");
		delete dyingTree;

		vector<string> answer;
		readFileByLines("checkFile.txt", answer);

		vector<string> result;
		readFileByLines(*iResults, result);

		if (answer != result)
		{
			cout << "Mistakes";
			exit(1);
		}
		++iData;
		++iResults;
	}
}