#include "pch.h"
#include <iostream>
#include "algorithms.h"
#include "readFile.h"
#include "dataStructures.h"


void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 10;

	for (int i = 0; i < debugNumber; i++)
	{
		if (0)
		{
			exit(1);
		}
	}
}

void checkFromFile()
{
	char *data[100] = {};
	const int linesRead = readFile("checkData.txt", data);

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		char *buffer = data[linesCounter];
		int result = -1;
		int period = -1;
		cyclicBiconnectedList enteredList;

		//обработать строку, добавив значения в список
		processDataString(buffer, &enteredList, &result, &period);

		//killThemAll
		killAllMenExceptN(&enteredList, period, 1);

		//сверить с результатом
		bool finalCheck = (result != -1) && (period != -1) && (result == deleteElementFromList(&enteredList, 1));
		if (!finalCheck)
		{
			printf("Ошибки");
			deleteList(&enteredList);
			exit(1);
		}
		deleteList(&enteredList);
	}
}