#include "pch.h"
#include <iostream>
#include "algorithms.h"
#include "readFile.h"

bool isSorted(int checkingArray[], int size)
{
	bool isSortedArray = true;
	for (int i = 1; i < size; i++)
	{
		if (checkingArray[i - 1] > checkingArray[i])
		{
			isSortedArray = false;
			break;
		}
	}

	return isSortedArray;
}


void autoGeneratedCheck()
{
	srand(0);
	const int debugNumber = 1000;
	const int maxRandomArrayElement = 25;
	const int maxArraySize = 20;

	for (int i = 0; i < debugNumber; i++)
	{
		const int arraySize = rand() % maxArraySize;
		int *checkingArray = new int[arraySize];

		for (int j = 0; j < arraySize; j++)
		{
			checkingArray[j] = rand() % maxRandomArrayElement;
		}

		shellSort(checkingArray, arraySize);

		if (!isSorted(checkingArray, arraySize))
		{
			printf("Массив не отсортирован: ");
			printArray(checkingArray, 0, arraySize - 1);
			delete[] checkingArray;
			exit(1);
		}
		delete[] checkingArray;
	}
}

void checkFromFile()
{
	char *data[100] = {};
	const int linesRead = readFile("checkData.txt", data);

	for (int linesCounter = 0; linesCounter < linesRead; linesCounter++)
	{
		if (0)
		{
			exit(1);
		}
	}
}